/**
 * @description Defines the base props for a controller generated by the CLI.
 * This can be modified, extended (composed) or removed as necessary.
 */
export type BaseControllerProps = {
  controllerName: string;
};
